apiVersion: striot.org/v1alpha1
kind: Topology
metadata:
  name: example-topology
spec:
  partitions:
    - id: 0
      image: adamcattermole/striot-src:latest
      connectType:
        ingress: "TCP"
        egress:  "KAFKA"
    - id: 1
      image: adamcattermole/striot-link:latest
      connectType:
        ingress: "KAFKA"
        egress:  "TCP"
    - id: 2
      image: adamcattermole/striot-sink:latest
      connectType:
        ingress: "TCP"
        egress:  "TCP"
  order: [0,1,2]
