apiVersion: apps/v1
kind: Deployment
metadata:
  name: striot-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: striot-operator
  template:
    metadata:
      labels:
        name: striot-operator
    spec:
      serviceAccountName: striot-operator
      containers:
        - name: striot-operator
          # Replace this with the built image name
          image: adamcattermole/striot-operator
          command:
          - striot-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "striot-operator"
